version: "2"

services:
  proxy:
    build: 
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    ports:
      - 80:80
  web:
    image: httpd
    volumes:
      - ./ignore:/usr/local/apache2/htdocs/
